### ISSUE TITLE
Attempted to call an undefined method named "getExampleByType" of class "Raml\Response". 

### ISSUE THREAD

**Issue by gfirm** [creads/api2symfony-bundle#13] opened 2016-03-21 10:12 UTC
The method not found, seem the method in other class name, the error caused by "vendor/creads/api2symfony/src/Converter/RamlConverter.php" line 64.

cread/api2symfony have different version between installed by composer and existing on repo https://github.com/creads/api2symfony/blob/master/src/Converter/RamlConverter.php.

Please compare...
Installed by composer : "vendor/creads/api2symfony/src/Converter/RamlConverter.php".
existing on repo : https://github.com/creads/api2symfony/blob/master/src/Converter/RamlConverter.php.

which one is used?
@pitpit @qpautrat @kix

**Comment by kix** [comment] 2016-03-21 10:18
@gfirm, sorry, but could you please be a bit more specific here? What's the expected behaviour here, and what happens instead? A stack trace and some reproduction steps would also be helpful, IMO. Please note I'm not a maintainer of this project, so basically I have no idea why would I be mentioned in this issue, but anyways, since you've got my attention :)

**Comment by qpautrat** [comment] 2016-03-21 10:19
Hi @gfirm ,
I don't really understand what is the problem here.
Can you give us more details please ?

**Comment by gfirm** [comment] 2016-03-21 10:22
I got this error message when I tried on console command
`[Symfony\Component\Debug\Exception\UndefinedMethodException]                              
  Attempted to call an undefined method named "getExampleByType" of class "Raml\Response".`

**Comment by qpautrat** [comment] 2016-03-21 10:31
Can you provide the RAML file you are currently using ?

**Comment by gfirm** [comment] 2016-03-21 10:33
I used your raml file sample 

> vendor/creads/api2symfony-bundle/tests/app/api.raml

**Comment by qpautrat** [comment] 2016-03-21 10:51
No problem with me.

Do you specified a version of `alecsammon/php-raml-parser` somewhere ?
As this bundle uses `creads/api2symfony` library you should have in your vendors the `php-raml-parser` in version `0.6.3`, as we can see [there](https://github.com/creads/api2symfony/blob/master/composer.json#L23).

**Comment by gfirm** [comment] 2016-03-21 11:05
yes, exactly same. I have the same version

**Comment by qpautrat** [comment] 2016-03-21 11:08
I don't understand, [it should not be possible](https://github.com/alecsammon/php-raml-parser/blob/0.6.3/src/Response.php#L59).

**Comment by gfirm** [comment] 2016-03-22 02:36
The problem is in here : **_vendor/api2symfony/src/Converter/RamlConverter.php" line 64_**.

and this is what I got from composer : 

```
<?php

namespace Creads\Api2Symfony\Converter;

use Raml\ApiDefinition;
use Raml\Parser;
use Raml\Resource;

use Creads\Api2Symfony\SymfonyController;
use Creads\Api2Symfony\SymfonyAction;
use Creads\Api2Symfony\SymfonyRoute;
use Creads\Api2Symfony\SymfonyResponse;

/**
 * Provide a way to convert a RAML specification to a list of SymfonyController
 *
 * @author Quentin <q.pautrat@creads.org>
 */
class RamlConverter implements ConverterInterface
{
    /**
     * Parser
     *
     * @var Parser
     */
    private $parser;

    /**
     * Constructor
     *
     * @param Parser $parser
     */
    public function __construct()
    {
        $this->parser = new Parser();
    }

    /**
     * Recursive method which converts raml resource into action and add it to controller
     *
     * @param  SymfonyController $controller Controller where actions will be added
     * @param  Resource $resource
     * @param  string   $chainName
     */
    protected function addActions(SymfonyController $controller, Resource $resource, $chainName = '')
    {
        $actions = array();

        $chainName = $chainName . '_' . strtolower($resource->getDisplayName());

        foreach ($resource->getMethods() as $method) {
            $actionName = strtolower($method->getType()) . str_replace(' ', '', ucwords(str_replace('_', ' ', $chainName))) . 'Action';
            $route = new SymfonyRoute($resource->getUri(), strtolower($method->getType() . $chainName));
            $action = new SymfonyAction($actionName, $route, $method->getType(), $method->getDescription());

            preg_match_all('/\{[a-zA-Z]+\}/', $resource->getUri(), $parameters);
            foreach ($parameters[0] as $parameter) {
                $action->addParameter(substr($parameter, 1, strlen($parameter) - 2));
            }

            if ($method->getResponses()) {
                foreach ($method->getResponses() as $code => $response) {
                    if (200 === $code) {
                        $action->setResponse(new SymfonyResponse($code, str_replace('\'', '\\\'', $controller->getExampleByType('application/json')), 'application/json'));
                    }
                }
            }

            $controller->addAction($action);
        }

        foreach ($resource->getResources() as $subresource) {
            $this->addActions($controller, $subresource, $chainName);
        }
    }

    /**
     * Build namespace given ApiDefinition and base namespace
     *
     * @param  ApiDefinition $definition Checks if definition has version
     * @param  string        $namespace  Base
     * @return string
     */
    protected function buildNamespace(ApiDefinition $definition, $namespace)
    {
        if ($definition->getVersion()) {
            $namespace .= '\\' . preg_replace('/[^a-zA-Z0-9]/', '_', $definition->getVersion());
        }

        return $namespace;
    }

    /**
     * {@inheritDoc}
     */
    public function convert($filename, $namespace)
    {
        $def = $this->parser->parse($filename);

        $namespace = $this->buildNamespace($def, $namespace);

        $controllers = array();

        if ($def->getResources()) {
            foreach ($def->getResources() as $resource) {

                $controller = new SymfonyController(ucfirst($resource->getDisplayName()) . 'Controller', $namespace, $resource->getDescription());
                $this->addActions($controller, $resource);
                $controllers[] = $controller;
            }
        }

        return $controllers;
    }
}
```

**Comment by qpautrat** [comment] 2016-03-22 09:35
I looked in the file's history
In any case we have this line `$controller->getExampleByType('application/json')` somewhere.
Moreover, you reported an `Undefined method in Raml\Response class` but in the code your are showing to us this method is called from `$controller`, which is a `SymfonyController` instance.
So it doesn't make any sense.

You can close it @pitpit I guess.

**Comment by gfirm** [comment] 2016-03-22 09:56
I know it's different with your script [here](https://github.com/creads/api2symfony/blob/master/src/Converter/RamlConverter.php), but the script that I shown is what I got base on [installation instruction](https://github.com/creads/api2symfony-bundle#user-content-installation) using composer.

If something went wrong with me, please give me the best way to install, cause I need it

**Comment by qpautrat** [comment] 2016-03-22 10:49
This is probably happening because of the `config.platform.php`. It overrides your native php version.
Last version of `api2symfony`is supposed to work with `alecsammon/php-raml-parser 0.6.3` which needs a php version `>=5.3.17`.
You can add in your `composer.json` in `require-dev` following statement:
`alecsammon/php-raml-parser": "0.6.3` and do a `composer update` to see what it tells you.

**Comment by gfirm** [comment] 2016-03-23 02:48
it works, thanks for your patient and explanation

**Closed as completed** 2016-03-23 03:09 UTC
